### ISSUE TITLE
Gitbook build stopped to work in node 12.18.3

### ISSUE THREAD

**Issue by mikyjpeg** [GitbookIO/gitbook-cli#110]
Since the new version, when running `gitbook build` it fails with the following error:

```
Installing GitBook 3.2.3

/home/travis/.nvm/versions/node/v12.18.3/lib/node_modules/gitbook-cli/node_modules/npm/node_modules/graceful-fs/polyfills.js:287
      if (cb) cb.apply(this, arguments)
                 ^
TypeError: cb.apply is not a function
    at /home/travis/.nvm/versions/node/v12.18.3/lib/node_modules/gitbook-cli/node_modules/npm/node_modules/graceful-fs/polyfills.js:287:18
    at FSReqCallback.oncomplete (fs.js:169:5)

The command "gitbook install" failed and exited with 1 during .
```

The command still works fine when using 12.18.2

**Comment by JoeyBling** [comment]
Yes, I have the same problem. My node version is `v14.6.0`

**Comment by SadSock** [comment]
I have the same problem.

**Comment by rjbeers** [comment]
I believe the issue was resolved by https://github.com/isaacs/node-graceful-fs/commit/168bdb8f0bb3174e8499d4bc5878deead4172c39, but gitbook-cli has outdated dependencies which pull in versions of graceful-fs without the fix.

**Comment by hitzhangjie** [comment]
I have the same problem, too.

node version is v14.6.0

**Comment by greyltc** [comment]
I guess we need to fork gitbook-cli to maintain it. Who wants to do it?

**Comment by JoeyBling** [comment]
@greyltc That sounds good. You can unify one person to fork and then maintain it through the open source community

**Comment by JoeyBling** [comment]
@rjbeers Thank you very much. You're right.
1. if you run `gitbook serve` has error and your `gitbook-cli` is installed globally.
Find the NPM global installation directory and into dir `node_modules/gitbook-cli/node_modules/npm/node_modules` Execute the order
> npm install graceful-fs@latest --save

2. if you run `gitbook install` has error
Go to user directory and into dir `.gitbook/versions/3.2.3/node_modules/npm` Execute the order
> npm install graceful-fs@latest --save

**Comment by zzaacchh** [comment]
@greyltc I noticed a new fork -- https://github.com/greyltc/gitbook-cli/commit/2b39017b9174841e89474c66b884d62fe7a0fdad .  Thanks!  Are you planning to publish your fork as an npm package?  Let me know if I can be any help.  Our team depends on gitbook-cli, so I'd love to find a path forward.

**Comment by greyltc** [comment]
@zzaacchh 
I rely on gitbook-cli as well and it's very unfortunate and frustrating that upstream support for it has been dropped (but hey, you can't always have your cake and eat it too!) and I would love a path forward too.
I would plan to publish my fork so that the community can have a working gitbook-cli, but I can't get it to work.

The NPM dependancy system seems to be a real nightmare. Any help is welcome.

**Comment by zzaacchh** [comment]
Thanks, @greyltc .  I'm planning to hire someone on upwork to help fork and repackage.  Any chance you'd be up for pitching in on the cost for that?

**Comment by greyltc** [comment]
The stuff I use gitbook-cli for is free, open and, non-revenue-generating, so unfortunately I don't have much other than a little of my time to offer. And that's not so valuble here because I don't know shit about javascript!

**Comment by vradars** [comment]
I was reached out by @zzaacchh. I’m happy to support this project for free! Forked.

**Comment by mxiaole** [comment]
> I believe the issue was resolved by [isaacs/node-graceful-fs@168bdb8](https://github.com/isaacs/node-graceful-fs/commit/168bdb8f0bb3174e8499d4bc5878deead4172c39), but gitbook-cli has outdated dependencies which pull in versions of graceful-fs without the fix.

yeah  it helps !!!   my node version is v14.5.0
thanks !!

**Comment by kimploo** [comment]
I ended up to use nvm to use nodejs 10 lts. I updated dependency of graceful-fs globally and locally but it won't help.

**Comment by rafauke** [comment]
I had the same issue but using different package. It was mentioned before that [selective dependency resolution](https://classic.yarnpkg.com/en/docs/selective-version-resolutions/) can help with that:

```js
"resolutions": {
  "**/graceful-fs": "^4.2.4"
  }
```

I am installing my deps with `yarn` and this fixed the issue. I think it's a good idea to double check if the version installed in `node_modules` is actually `4.2.4` - maybe a lock file or cache keeps installing other version.

**Comment by gengjiawen** [comment]
I make my own fork, if you are interested, just use `npm i -g gengjiawen/gitbook-cli` should work.

I also develop an github action for this, please refer to: https://github.com/gengjiawen/koajs-design-note.

**Comment by k8w** [comment]
Still +1

**Comment by jinifor** [comment]
I had same problem.
I think seems to be dependancy problem with latest version for graceful-fs.
Change the graceful-fs version solves the problem.

My environment is : 
- OS : macOS Big Sur
- node : v12.22.1
- npm : v6.14.12
- gitbook-cli : gitbook-cli@2.3.2
- graceful-fs : 4.1.4

try this : 

$ npm i -g gitbook-cli
$ cd /usr/local/lib/node_modules/gitbook-cli
$ npm i graceful-fs@4.1.4 --save
$ cd /usr/local/lib/node_modules/gitbook-cli/node_modules/npm
$ npm i graceful-fs@4.1.4 --save
$ cd {your gitbook directory}
$ gitbook init
$ gitbook serve
>info: 7 plugins are installed 
>info: loading plugin "livereload"... OK 
>info: loading plugin "highlight"... OK 
>info: loading plugin "search"... OK 
>info: loading plugin "lunr"... OK 
>info: loading plugin "sharing"... OK 
>info: loading plugin "fontsettings"... OK 
>info: loading plugin "theme-default"... OK 
>info: found 1 pages 
>info: found 0 asset files 
>info: >> generation finished with success in 0.2s ! 
>
>Starting server ...
>Serving book on http://localhost:4000
>

**Comment by sbyeol3** [comment]
> I had same problem.
> I think seems to be dependancy problem with latest version for graceful-fs.
> Change the graceful-fs version solves the problem.
> 
> My environment is :
> 
> * OS : macOS Big Sur
> * node : v12.22.1
> * npm : v6.14.12
> * gitbook-cli : gitbook-cli@2.3.2
> * graceful-fs : 4.1.4
> 
> try this :
> 
> $ npm i -g gitbook-cli
> $ cd /usr/local/lib/node_modules/gitbook-cli
> $ npm i graceful-fs@4.1.4 --save
> $ cd /usr/local/lib/node_modules/gitbook-cli/node_modules/npm
> $ npm i graceful-fs@4.1.4 --save
> $ cd {your gitbook directory}
> $ gitbook init
> $ gitbook serve
> 
> > info: 7 plugins are installed
> > info: loading plugin "livereload"... OK
> > info: loading plugin "highlight"... OK
> > info: loading plugin "search"... OK
> > info: loading plugin "lunr"... OK
> > info: loading plugin "sharing"... OK
> > info: loading plugin "fontsettings"... OK
> > info: loading plugin "theme-default"... OK
> > info: found 1 pages
> > info: found 0 asset files
> > info: >> generation finished with success in 0.2s !
> > Starting server ...
> > Serving book on http://localhost:4000

It works for me :) Thanks 😋

- npm : v7.18.1
- node : v16.4.0

**Comment by laurieliyang** [comment]
> I had same problem.
> I think seems to be dependancy problem with latest version for graceful-fs.
> Change the graceful-fs version solves the problem.
> 
> My environment is :
> 
> * OS : macOS Big Sur
> * node : v12.22.1
> * npm : v6.14.12
> * gitbook-cli : gitbook-cli@2.3.2
> * graceful-fs : 4.1.4
> 
> try this :
> 
> $ npm i -g gitbook-cli
> $ cd /usr/local/lib/node_modules/gitbook-cli
> $ npm i graceful-fs@4.1.4 --save
> $ cd /usr/local/lib/node_modules/gitbook-cli/node_modules/npm
> $ npm i graceful-fs@4.1.4 --save
> $ cd {your gitbook directory}
> $ gitbook init
> $ gitbook serve
> 
> > info: 7 plugins are installed
> > info: loading plugin "livereload"... OK
> > info: loading plugin "highlight"... OK
> > info: loading plugin "search"... OK
> > info: loading plugin "lunr"... OK
> > info: loading plugin "sharing"... OK
> > info: loading plugin "fontsettings"... OK
> > info: loading plugin "theme-default"... OK
> > info: found 1 pages
> > info: found 0 asset files
> > info: >> generation finished with success in 0.2s !
> > Starting server ...
> > Serving book on http://localhost:4000

It works for me too !!!  Thanks @jinifor

**Comment by evilrussian** [comment]
Workaround for me in node:v14.16.0
```bash
$ yarn global add gitbook-cli@2.2.0
$ gitbook fetch 3.2.3
```

**Comment by lianghuipinglz** [comment]
My node version is `v14.0.0` 
"gitbook install"  can success

**Comment by nakov** [comment]
Just replace the failing `polyfills.js` with this one:
https://raw.githubusercontent.com/isaacs/node-graceful-fs/168bdb8f0bb3174e8499d4bc5878deead4172c39/polyfills.js

**Comment by nakov** [comment]
These are the detailed steps to fix the problem (temporary, just to execute `gitbook install` and `gitbook build`):

#### Install `gitbook-cli` globally (if not already installed)
`npm -g install gitbook-cli`

#### Go to your NPM global modules directory (find its location by typing `npm -g list`)
Linux: `cd /usr/lib/node_modules`
Windows: `cd %AppData%/npm/node_modules`

#### Go to the `graceful-fs` folder
`cd gitbook-cli/node_modules/npm/node_modules/graceful-fs`

#### Delete the old incompatible file `polyfills.js`, which causes `TypeError: cb.apply is not a function`
`rm polyfills.js`

#### Download a fixed newer version of `polyfills.js` from GitHub
`wget https://raw.githubusercontent.com/isaacs/node-graceful-fs/168bdb8f0bb3174e8499d4bc5878deead4172c39/polyfills.js`

**Comment by MaDolphin** [comment]
> I had same problem. I think seems to be dependancy problem with latest version for graceful-fs. Change the graceful-fs version solves the problem.
> 
> My environment is :
> 
> * OS : macOS Big Sur
> * node : v12.22.1
> * npm : v6.14.12
> * gitbook-cli : gitbook-cli@2.3.2
> * graceful-fs : 4.1.4
> 
> try this :
> 
> $ npm i -g gitbook-cli $ cd /usr/local/lib/node_modules/gitbook-cli $ npm i graceful-fs@4.1.4 --save $ cd /usr/local/lib/node_modules/gitbook-cli/node_modules/npm $ npm i graceful-fs@4.1.4 --save $ cd {your gitbook directory} $ gitbook init $ gitbook serve
> 
> > info: 7 plugins are installed
> > info: loading plugin "livereload"... OK
> > info: loading plugin "highlight"... OK
> > info: loading plugin "search"... OK
> > info: loading plugin "lunr"... OK
> > info: loading plugin "sharing"... OK
> > info: loading plugin "fontsettings"... OK
> > info: loading plugin "theme-default"... OK
> > info: found 1 pages
> > info: found 0 asset files
> > info: >> generation finished with success in 0.2s !
> > Starting server ...
> > Serving book on http://localhost:4000

Great!! It works for me.

**Comment by geeknees** [comment]
https://github.com/GitbookIO/gitbook-cli/issues/110#issuecomment-863706455
This works for me too. I'm using M1 mac + homebrew and changed the PATH, so I need to make the following changes.


```bash
npm i -g gitbook-cli
cd /opt/homebrew/lib/node_modules/gitbook-cli
npm i graceful-fs@4.1.4 --save
cd /opt/homebrew/lib/node_modules/gitbook-cli/node_modules/npm
npm i graceful-fs@4.1.4 --save
cd {your gitbook directory}
gitbook init
gitbook serve
```

**Comment by VaneHay** [comment]
> I had same problem. I think seems to be dependancy problem with latest version for graceful-fs. Change the graceful-fs version solves the problem.
> 
> My environment is :
> 
> * OS : macOS Big Sur
> * node : v12.22.1
> * npm : v6.14.12
> * gitbook-cli : gitbook-cli@2.3.2
> * graceful-fs : 4.1.4
> 
> try this :
> 
> $ npm i -g gitbook-cli $ cd /usr/local/lib/node_modules/gitbook-cli $ npm i graceful-fs@4.1.4 --save $ cd /usr/local/lib/node_modules/gitbook-cli/node_modules/npm $ npm i graceful-fs@4.1.4 --save $ cd {your gitbook directory} $ gitbook init $ gitbook serve
> 
> > info: 7 plugins are installed
> > info: loading plugin "livereload"... OK
> > info: loading plugin "highlight"... OK
> > info: loading plugin "search"... OK
> > info: loading plugin "lunr"... OK
> > info: loading plugin "sharing"... OK
> > info: loading plugin "fontsettings"... OK
> > info: loading plugin "theme-default"... OK
> > info: found 1 pages
> > info: found 0 asset files
> > info: >> generation finished with success in 0.2s !
> > Starting server ...
> > Serving book on http://localhost:4000

thank you! it is working...

**Comment by wanghao6736** [comment]
> These are the detailed steps to fix the problem (temporary, just to execute `gitbook install` and `gitbook build`):
> 
> #### Install `gitbook-cli` globally (if not already installed)
> `npm -g install gitbook-cli`
> 
> #### Go to your NPM global modules directory (find its location by typing `npm -g list`)
> Linux: `cd /usr/lib/node_modules` Windows: `cd %AppData%/npm/node_modules`
> 
> #### Go to the `graceful-fs` folder
> `cd gitbook-cli/node_modules/npm/node_modules/graceful-fs`
> 
> #### Delete the old incompatible file `polyfills.js`, which causes `TypeError: cb.apply is not a function`
> `rm polyfills.js`
> 
> #### Download a fixed newer version of `polyfills.js` from GitHub
> `wget https://raw.githubusercontent.com/isaacs/node-graceful-fs/168bdb8f0bb3174e8499d4bc5878deead4172c39/polyfills.js`

that's helpful! I finally manage to install gitbook with node `v16.14.1`

**Comment by minhnguyenvan95** [comment]
+ 1

**Comment by dbhuang** [comment]
node -v 16.14.2  npm -v 8.5.0
node -v v17.9.0  npm -v 8.7.0

I tried to install graceful-fs@latest(graceful-fs@4.2.10), but when I finished, the Gitbook was gone.  Finally, graceful-fs@4.2.0 was installed to fix the problem

**Comment by dbhuang** [comment]
node -v 16.14.2  npm -v 8.5.0
node -v 17.9.0  npm -v 8.7.0

I tried to install graceful-fs@latest(graceful-fs@4.2.10), but when I finished, the Gitbook was gone.  Finally, graceful-fs@4.2.0 was installed to fix the problem

**Comment by marc-spinozza** [comment]
To anyone still having this issue, I have setup an devcontainer environment with gitbook configured and working fine.

[devcontainer-gitbook](https://github.com/marc-spinozza/devcontainer-gitbook)

Hope it can help someone!

**Comment by gurezo** [comment]
I have the same problem.
my pc develop enviroment

```
macOS Monterey v12.6
$ node -v 
v16.17.0
$ npm -v
8.15.0
$ yarn -v
1.22.19
$ ruby -v
ruby 2.6.8p205 (2021-07-07 revision 67951) [universal.arm64e-darwin21]
```

**Comment by nakov** [comment]
I use GitHub Actions script to build and deploy my gitbook-based books. This is the script. It works successfully in the last 3 years: https://github.com/SoftUni/Programming-Basics-Book-JS-EN/blob/master/.github/workflows/gitbook-deploy.yml

**Comment by uudiin** [comment]
I have the same problem, too.

please help.

node version is v18.14.0.

**Comment by mahula** [comment]
This problem still exists.
Any workaround or solutions instead of usin NodeJS <=12.18.2?

**Comment by gengjiawen** [comment]
> This problem still exists. Any workaround or solutions instead of usin NodeJS <=12.18.2?

https://github.com/GitbookIO/gitbook-cli/issues/110#issuecomment-803897429 this works on Node.js 22.

**Comment by bruce256** [comment]
`$ npm install -g gitbook-cli@2.2.0
$ gitbook fetch 3.2.3`

it works for me, in Windows, node 10.8.1

**Comment by 2233466866** [comment]
有人解决了这个问题！
誰かがこの問題を解決した！
누군가가 이 문제를 해결했다!
Someone has solved this problem!
↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓
https://github.com/gofulljs/gbook
